### ISSUE TITLE
Speed tests

### ISSUE THREAD

**Issue by briatte** [sctyner/ggnet-paper#4]
The speed-tests part of the paper is [harder than expected](https://github.com/sctyner/ggnet-paper/commit/19991a2bc71113c39663b3d95e91ef4394054de8).

The tests on **random graphs** are not producing the same results for @heike and for me; I'm now also running the tests on an old MacBook running Linux Xubuntu, and the results are different again.

Here's what I get:

![screen shot 2015-11-01 at 21 50 06](https://cloud.githubusercontent.com/assets/322533/10871275/ae5f4508-80e2-11e5-8ae6-b1ec45467760.png)

It could be due to the "print results" part of the tests. Perhaps we should save to file as PDF instead, but that would just bias the test differently by getting I/O speed into it.

The tests on the **protein network** are strange on my end: [this script](https://github.com/sctyner/ggnet-paper/blob/master/runtimes-protein/run.r) produces highly homogenous runtimes that are so close to each other that they do not form boxplots.

**Comment by briatte** [comment]
P.S. @heike just saw your emails—your results have a lot more variance than mine… Something's definitely weird here, even my Linux tests have less variance than that.

**Comment by briatte** [comment]
Linux box output:

![runtimes](https://cloud.githubusercontent.com/assets/322533/10871807/1f06619c-80f2-11e5-8c04-6e10942989a1.jpg)

**Comment by sctyner** [comment]
Here are my results: 

[runtimes.pdf](https://github.com/sctyner/ggnet-paper/files/24986/runtimes.pdf)

**Comment by sctyner** [comment]
![image](https://cloud.githubusercontent.com/assets/6137322/10872572/734dd6e0-80ca-11e5-8c22-143358d56460.png)

1.3 GHz Intel Core i5 
Intel HD Graphics 5000 1536 MB

**Comment by sctyner** [comment]
If we are going to include igraph in these runtime tests, shouldn't we also include it in the protein runtime tests?  Alternatively, we could remove all igraph results from the current runtime tests. But since we already have them, I'm going to just add some igraph testing to the protein runtimes test.

**Comment by heike** [comment]
igraph should go into the protein run test - I agree

**Comment by sctyner** [comment]
Oh, it was already added in the code, but was not showing up in the paper. Fixing now.

**Comment by heike** [comment]
ah, I just included it - that's going to clash!

**Comment by briatte** [comment]
Sam's results are somewhat close to what I get.

I'm completely startled by the huge qualitative differences from one setup to another!

**Comment by heike** [comment]
have a look at the paper - we included all eight approaches in one figure -
and I think it works pretty well. Your results and mine are about as
different as possible. What we did not take into account is that the K-K
layout might need a different amount of time from an F-R layout. That's one
thing that we still need to rule out.

**Comment by briatte** [comment]
Just had a look at the paper, the multiple tests are interesting and the single plot works perfectly IMO. I'll add the runtimes from my old Linux/MacBook machine this week.

**Comment by heike** [comment]
Great! It's easy to add another set of runtimes (as long as it is a full
set) ... just name the folder accordingly and put it into the runtimes
folder. The script in the paper will pull it out correctly and place it in
the paper.

**Comment by briatte** [comment]
Closing this issue since we are almost ready to submit.
